### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by faikit** [jzuern/lanegnn#1]
Hi, is the [requirements.txt](https://github.com/jzuern/lanegnn/blob/main/urbanlanegraph_dataset/requirements.txt) correct? It seems not to be in normal format, and i got an error when installing:
```
> pip install -r requirements.txt
ERROR: Invalid requirement: '_libgcc_mutex=0.1=conda_forge' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```

**Comment by jzuern** [comment]
Hi @faikit, thanks for raising this issue.

We changed the requirements to an environment.yml file and updated the downloading instructions accordingly in 1ad7a8ca1d2aa1c32cec2b43a0d8a3adc3dc1a99.
