### ISSUE TITLE
Need to obtain translation matrix between ULG aerial image and Av2 city coordinate system?

### ISSUE THREAD

**Issue by sephyli** [jzuern/lanegnn#2]
Hello,

I am trying to work with satellite images in UrbanLaneGraph Dataset, great works.
I need to be able to translate coordinates between the satellite image coordinate system and the Av2 city coordinate system around all 6 city.

Can you please provide any information or resources that would help me obtain this correspondence? I appreciate any assistance you can provide.

Thank you.

**Comment by jzuern** [comment]
Thanks for raising this issue, @sephyli 

We added a `helper.py` file in 0888f31688dfb3a4e971deb42275bfb0b484f8d1, where we include functions to transform the AV2  coordinates into the image pixel coordinates of our dataset. Let us know if you have any questions.
