### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by zym1119** [jzuern/lanegnn#3]
Hello,
I want to use your code and dataset for better understanding of your great work in CVPR.

Will a pretrained model released later? Cause i have no enough GPU for training a good model.

Thanks for your reply.

**Comment by jzuern** [comment]
Hi @zym1119 
Thank you for bringing up this issue. We appreciate your interest in obtaining the weights, but unfortunately, it is not possible for us to publish them at this time due to legal restrictions.
