### ISSUE TITLE
Training guidance

### ISSUE THREAD

**Issue by zzzjoey** [jzuern/lanegnn#5]
Hi, thank you for your excellent open-source work!

I would like to train the model according to the code, but I may encounter some errors such as missing data preparation modules. Could you please  provide some guidance or readme file for training the model?

Thanks for your reply.

**Comment by jzuern** [comment]
Hi @zou-yiqi,
We are working on making this part of the code available as well. Please stay tuned :)

**Comment by jzuern** [comment]
In f92d97fc15714e5fff4462230b6f7001600bd4f9, we added the data preparation module available as well. 

The training scripts for the models are in https://github.com/jzuern/lanegnn/tree/main/methods, along with a [TRAINING.md](https://github.com/jzuern/lanegnn/tree/main/methods/TRAINING.md) Readme file. 

Please let us know if you have specific follow-up questions.

Best,
Jannik
